Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/boot2docker"
  config.vm.network :forwarded_port, host: 5672, guest: 5672
  config.vm.network :forwarded_port, host: 15672, guest: 15672
end
