Vagrant.configure("2") do |config|
  config.vm.define "sftp" do |sftp|
    sftp.vm.provider "docker" do |d|
      d.vagrant_vagrantfile = "./docker-host-vm/Vagrantfile"
      d.image = "atmoz/sftp"
      d.ports = [ "3022:22" ]
    end
  end
  config.vm.provision "docker" do |d|
    d.run 'atmoz/sftp',
      args: "foo:123:1001"
  end
end
