Vagrant.configure("2") do |config|
  config.vm.define "mariadb" do |mariadb|
    mariadb.vm.provider "docker" do |d|
      d.vagrant_vagrantfile = "./docker-host-vm/Vagrantfile"
      d.image = "library/mariadb"
      d.ports = [ "3306:3306" ]
      d.env = { MYSQL_ROOT_PASSWORD: '123456' }
    end
    mariadb.vm.provision "docker" do |d|
      d.run "mariadb:10.0.22"
    end
  end
end
