Vagrant.configure("2") do |config|
  config.vm.define "redis" do |redis|
    redis.vm.provider "docker" do |d|
      d.vagrant_vagrantfile = "./docker-host-vm/Vagrantfile"
      d.image = "library/redis"
      d.ports = [ "6379:6379" ]
    end
  end
end
