Vagrant.configure("2") do |config|
  config.vm.define "rabbitmq" do |rabbitmq|
    rabbitmq.vm.provider "docker" do |d|
      d.vagrant_vagrantfile = "./docker-host-vm/Vagrantfile"
      d.image = "library/rabbitmq"
      d.ports = [ "5672:5672", "15672:15672" ]
      d.env = { RABBITMQ_ERLANG_COOKIE: 'secretcookiehere' }
    end
    rabbitmq.vm.provision "docker" do |d|
      d.run "rabbitmq:3.6-management"
    end
  end
end
