Vagrant.configure("2") do |config|
  config.vm.define "mongo" do |mongo|
    mongo.vm.provider "docker" do |d|
      d.vagrant_vagrantfile = "./docker-host-vm/Vagrantfile"
      d.image = "library/mongo"
      d.ports = [ "27017:27017" ]
    end
  end
end
