Vagrant.configure("2") do |config|
  config.vm.define "mysql" do |mysql|
    mysql.vm.provider "docker" do |d|
      d.vagrant_vagrantfile = "./docker-host-vm/Vagrantfile"
      d.image = "library/mysql"
      d.ports = [ "3306:3306" ]
      d.env = { MYSQL_ROOT_PASSWORD: '123456' }
    end
    mysql.vm.provision "docker" do |d|
      d.run "mysql:5.6"
    end
  end
end
